### ISSUE TITLE
Individual stats per device

### ISSUE THREAD

**Issue by StefanBrand** [lineageos-infra/tribble-tracker#6]
Hello, some time ago there were individual stats for devices above 1.000 LOS installs. Now, that page isn't even available for the bacon: https://stats.lineageos.org/model/bacon

Will the feature return at some point? (Specifically I'm interested in the [individual stats of FP2](https://stats.lineageos.org/model/FP2).)

**Comment by zifnab06** [comment]
It was added when this project was moved from mongo -> postgres. Enjoy!

**Comment by StefanBrand** [comment]
Yep, works great, thanks! :) 
-- 
Diese Nachricht wurde von meinem Fairphone mit K-9 Mail gesendet.

Am 10. Oktober 2018 07:14:20 MESZ schrieb Tom Powell <notifications@github.com>:
>It was added when this project was moved from mongo -> postgres. Enjoy!
